from examples.nst_letters import run_experiment_nst
from examples.two_fans import run_experiment_fans
from examples.pendulum import run_experiment_pendulum
from examples.big_network import run_experiment_bignet
